import os
import re
from pathlib import Path
from typing import Optional
from app.core.config import settings

SAFE_UUID_REGEX = re.compile(r"^[a-f0-9\-]{32,36}$", re.IGNORECASE)


def resolve_excel_file_path(file_id: str, owner_id: Optional[str] = None) -> Path:
    """
    Securely resolves an Excel file_id to its absolute local path.
    Enforces:
    1. Valid UUID structure (blocks path traversal in file_id).
    2. Searches strictly within designated local storage directories:
       - settings.UPLOAD_DIR (user uploaded documents)
       - generated_files directory (files generated by MRPL AI)
    3. Verifies file existence and jail boundary.
    4. Optional owner verification when metadata companion file exists.
    """
    if not SAFE_UUID_REGEX.match(file_id):
        raise ValueError("Invalid file_id format.")

    upload_dir = Path(settings.UPLOAD_DIR).resolve()
    generated_dir = (upload_dir.parent / "generated_files").resolve()

    candidate_paths = [
        # Check generated files first
        generated_dir / f"{file_id}.xlsx",
        # Check uploads directory (filename might be file_id.xlsx or file_id)
        upload_dir / f"{file_id}.xlsx",
        upload_dir / file_id,
    ]

    # Also check if there is an uploaded file matching file_id in document storage
    # E.g. upload_dir might contain files stored with file_id prefix
    if upload_dir.exists():
        for p in upload_dir.glob(f"{file_id}*"):
            if p.is_file() and (p.suffix.lower() in (".xlsx", ".xlsm") or not p.suffix):
                candidate_paths.append(p)

    target_path: Optional[Path] = None
    for cp in candidate_paths:
        if cp.exists() and cp.is_file():
            # Jail check
            resolved = cp.resolve()
            if resolved.is_relative_to(upload_dir) or resolved.is_relative_to(generated_dir):
                target_path = resolved
                break

    if not target_path:
        raise FileNotFoundError(f"Workbook with ID '{file_id}' not found in authorized storage.")

    # Owner validation if metadata companion exists
    meta_path = target_path.parent / f"{file_id}.json"
    if meta_path.exists() and owner_id:
        import json
        try:
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
            if meta.get("owner_id") and meta.get("owner_id") != owner_id:
                raise PermissionError("Access denied: You do not own this file.")
        except json.JSONDecodeError:
            pass

    return target_path
