import io
import re
from typing import Optional, List
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Preformatted
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to add 'Page X of Y' and header to all pages.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        # Running Header
        self.drawString(54, 750, "MRPL AI — Confidential Document Report")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 744, 558, 744)

        # Running Footer
        self.line(54, 45, 558, 45)
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 32, page_str)
        self.drawString(54, 32, "Generated by MRPL Sovereign AI Assistant")
        self.restoreState()


def _format_markdown_inline(text: str) -> str:
    """Converts basic markdown bold/italics to ReportLab XML tags."""
    # Escape XML entities first
    res = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    # Bold **text** -> <b>text</b>
    res = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', res)
    # Italic *text* -> <i>\1</i>
    res = re.sub(r'\*([^*]+?)\*', r'<i>\1</i>', res)
    # Inline code `text` -> <font face="Courier">\1</font>
    res = re.sub(r'`([^`]+?)`', r'<font face="Courier" color="#0F172A"><b>\1</b></font>', res)
    return res


def export_to_pdf(content: str, title: Optional[str] = None) -> bytes:
    """
    Converts markdown content into a professionally styled PDF report using ReportLab Platypus.
    Returns bytes of the PDF.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=64,
        bottomMargin=54
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#0F172A"),
        spaceAfter=12
    )

    h1_style = ParagraphStyle(
        'DocH1',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#0F172A"),
        spaceBefore=12,
        spaceAfter=6
    )

    h2_style = ParagraphStyle(
        'DocH2',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#1E293B"),
        spaceBefore=10,
        spaceAfter=4
    )

    h3_style = ParagraphStyle(
        'DocH3',
        parent=styles['Heading3'],
        fontName='Helvetica-Bold',
        fontSize=10.5,
        leading=14,
        textColor=colors.HexColor("#334155"),
        spaceBefore=8,
        spaceAfter=3
    )

    body_style = ParagraphStyle(
        'DocBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13.5,
        textColor=colors.HexColor("#1E293B"),
        spaceAfter=4
    )

    bullet_style = ParagraphStyle(
        'DocBullet',
        parent=body_style,
        leftIndent=16,
        firstLineIndent=-10,
        spaceAfter=2
    )

    code_style = ParagraphStyle(
        'DocCode',
        parent=styles['Normal'],
        fontName='Courier',
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#0F172A"),
        backColor=colors.HexColor("#F8FAFC"),
        borderColor=colors.HexColor("#E2E8F0"),
        borderWidth=0.5,
        borderPadding=6,
        spaceBefore=4,
        spaceAfter=6
    )

    flowables = []

    # Document Title
    if title:
        flowables.append(Paragraph(_format_markdown_inline(title), title_style))
        flowables.append(Spacer(1, 6))

    lines = content.splitlines()
    i = 0
    in_code_block = False
    code_lines: List[str] = []

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # 1. Code Block
        if stripped.startswith("```"):
            if in_code_block:
                code_text = "\n".join(code_lines)
                flowables.append(Preformatted(code_text, code_style))
                code_lines = []
                in_code_block = False
            else:
                in_code_block = True
                code_lines = []
            i += 1
            continue

        if in_code_block:
            code_lines.append(line)
            i += 1
            continue

        # Blank line
        if not stripped:
            i += 1
            continue

        # 2. Markdown Table
        if stripped.startswith("|") and stripped.endswith("|"):
            table_raw = []
            while i < len(lines) and lines[i].strip().startswith("|") and lines[i].strip().endswith("|"):
                row_str = lines[i].strip()
                if re.match(r"^\|(\s*:?-+:?\s*\|)+$", row_str):
                    i += 1
                    continue
                cells = [c.strip() for c in row_str.strip("|").split("|")]
                table_raw.append(cells)
                i += 1

            if table_raw:
                num_cols = max(len(r) for r in table_raw)
                table_data = []
                for r_idx, row in enumerate(table_raw):
                    padded_row = []
                    is_header = (r_idx == 0)
                    for c_idx in range(num_cols):
                        val = row[c_idx] if c_idx < len(row) else ""
                        formatted_val = _format_markdown_inline(val)
                        if is_header:
                            header_p_style = ParagraphStyle(
                                'TH',
                                parent=body_style,
                                fontName='Helvetica-Bold',
                                fontSize=9,
                                leading=11,
                                textColor=colors.white
                            )
                            padded_row.append(Paragraph(formatted_val, header_p_style))
                        else:
                            cell_p_style = ParagraphStyle(
                                'TD',
                                parent=body_style,
                                fontSize=8.5,
                                leading=11,
                                textColor=colors.HexColor("#1E293B")
                            )
                            padded_row.append(Paragraph(formatted_val, cell_p_style))
                    table_data.append(padded_row)

                # Available width = 504 pt (612 - 54*2)
                col_w = 504.0 / num_cols
                t = Table(table_data, colWidths=[col_w] * num_cols)
                
                t_styles = [
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0F172A")),
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                    ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                    ('TOPPADDING', (0, 0), (-1, -1), 4),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ]
                for r_idx in range(1, len(table_data)):
                    if r_idx % 2 == 1:
                        t_styles.append(('BACKGROUND', (0, r_idx), (-1, r_idx), colors.HexColor("#F8FAFC")))

                t.setStyle(TableStyle(t_styles))
                flowables.append(t)
                flowables.append(Spacer(1, 8))
            continue

        # 3. Headings
        if stripped.startswith("# "):
            flowables.append(Paragraph(_format_markdown_inline(stripped[2:].strip()), h1_style))
            i += 1
            continue

        if stripped.startswith("## "):
            flowables.append(Paragraph(_format_markdown_inline(stripped[3:].strip()), h2_style))
            i += 1
            continue

        if stripped.startswith("### "):
            flowables.append(Paragraph(_format_markdown_inline(stripped[4:].strip()), h3_style))
            i += 1
            continue

        # 4. Bullet lists (* or -)
        if re.match(r"^[\*\-]\s+", stripped):
            text_part = re.sub(r"^[\*\-]\s+", "", stripped)
            formatted = f"&bull;  {_format_markdown_inline(text_part)}"
            flowables.append(Paragraph(formatted, bullet_style))
            i += 1
            continue

        # 5. Numbered lists (1. )
        num_match = re.match(r"^(\d+)\.\s+(.*)", stripped)
        if num_match:
            num = num_match.group(1)
            text_part = num_match.group(2)
            formatted = f"{num}.  {_format_markdown_inline(text_part)}"
            flowables.append(Paragraph(formatted, bullet_style))
            i += 1
            continue

        # 6. Standard paragraph
        flowables.append(Paragraph(_format_markdown_inline(stripped), body_style))
        i += 1

    doc.build(flowables, canvasmaker=NumberedCanvas)
    return buffer.getvalue()
